In [1]:
"""Bag of Words"""

'Bag of Words'

In [2]:
import pandas as pd


df = pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df["Category"].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df["Spam"] = df["Category"].apply(lambda x: 1 if x == "spam" else 0)
df.head()

,Category,Message,Spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df["Message"], df["Spam"], test_size=0.25, random_state=0)

In [6]:
print(f"X_train size: {X_train.shape}")
print(f"X_test size: {X_test.shape}")
print(f"y_train size: {y_train.shape}")
print(f"y_train size: {y_test.shape}")

X_train size: (4179,)
X_test size: (1393,)
y_train size: (4179,)
y_train size: (1393,)


In [7]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train.values)

In [8]:
X_train_vectorized.shape

(4179, 7541)

In [9]:
X_train_vectorized.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7541))

In [10]:
vectorizer.get_feature_names_out()[-1]

'〨ud'

In [11]:
vectorizer.vocabulary_

{'its': 3671,
 'going': 3085,
 'good': 3095,
 'no': 4658,
 'problem': 5289,
 'but': 1521,
 'still': 6310,
 'need': 4588,
 'little': 4044,
 'experience': 2625,
 'to': 6759,
 'understand': 6959,
 'american': 911,
 'customer': 2053,
 'voice': 7128,
 'have': 3262,
 'secret': 5812,
 'admirer': 797,
 'reveal': 5610,
 'who': 7302,
 'thinks': 6676,
 'so': 6122,
 'special': 6202,
 'call': 1548,
 '09065174042': 214,
 'opt': 4830,
 'out': 4871,
 'reply': 5563,
 'stop': 6321,
 '50': 528,
 'per': 5008,
 'msg': 4488,
 'recd': 5470,
 'cust': 2050,
 'care': 1593,
 '07821230901': 36,
 'ok': 4779,
 'huh': 3444,
 'hyde': 3468,
 'park': 4947,
 'not': 4692,
 'in': 3546,
 'mel': 4311,
 'ah': 846,
 'opps': 4829,
 'got': 3112,
 'confused': 1894,
 'anyway': 971,
 'if': 3500,
 'tt': 6883,
 'best': 1274,
 'choice': 1733,
 'den': 2165,
 'we': 7223,
 'juz': 3784,
 'take': 6515,
 'it': 3664,
 'just': 3779,
 'hopeing': 3397,
 'that': 6639,
 'wasn': 7199,
 'too': 6797,
 'pissed': 5086,
 'up': 6999,
 'remember': 5533,

In [12]:
import numpy as np


np.where(X_train_vectorized.toarray()[0] != 0)

(array([ 911, 1521, 2053, 2625, 3085, 3095, 3671, 4044, 4588, 4658, 5289,
        6310, 6759, 6959, 7128]),)

In [13]:
# Build machine learning model
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [14]:
X_test_vectorizer = vectorizer.transform(X_test)
y_prediction = model.predict(X_test_vectorizer)
y_prediction

array([0, 1, 0, ..., 1, 0, 0], shape=(1393,))

In [15]:
from sklearn.metrics import accuracy_score, classification_report

print((f"Accuracy: {accuracy_score(y_test, y_prediction)}"))
print(f"Classification Report: \n {classification_report(y_test, y_prediction)}")

Accuracy: 0.9877961234745154
Classification Report: 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.99      0.92      0.95       185

    accuracy                           0.99      1393
   macro avg       0.99      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



In [16]:
emails = [
    "Hey mohan, can we get together to watch footbal game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"
]

emails_count_vector = vectorizer.transform(emails)
model.predict(emails_count_vector)

array([0, 1])

In [17]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("naive_bayes_classifier", MultinomialNB()), 
])

In [18]:
pipeline.fit(X_train, y_train)

,steps,"[('vectorizer', ...), ('naive_bayes_classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [19]:
emails = [
    "Hey mohan, can we get together to watch footbal game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"
]

pipeline.predict(emails)

array([0, 1])

In [20]:
print((f"Accuracy: {accuracy_score(y_test, pipeline.predict(X_test))}"))
print(f"Classification Report: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy: 0.9877961234745154
Classification Report: 
               precision    recall  f1-score   support

           0       0.99      1.00      0.99      1208
           1       0.99      0.92      0.95       185

    accuracy                           0.99      1393
   macro avg       0.99      0.96      0.97      1393
weighted avg       0.99      0.99      0.99      1393



In [21]:
"""Exercise"""
import pandas as pd
# Load the dataset
df = pd.read_csv("IMDB Dataset.csv")
df.head()

,review,sentiment
0,One of the other reviewers has mentioned that ...,positive
1,A wonderful little production. <br /><br />The...,positive
2,I thought this was a wonderful way to spend ti...,positive
3,Basically there's a family where a little boy ...,negative
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive


In [22]:
# Print the shape of the dataset
df.shape

(50000, 2)

In [23]:
df["sentiment"].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [24]:
df["sentiment_boolean"] = df["sentiment"].apply(lambda x: 1 if x == "positive" else 0)
df.head()

,review,sentiment,sentiment_boolean
0,One of the other reviewers has mentioned that ...,positive,1
1,A wonderful little production. <br /><br />The...,positive,1
2,I thought this was a wonderful way to spend ti...,positive,1
3,Basically there's a family where a little boy ...,negative,0
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1


In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df["review"], df["sentiment_boolean"], test_size=0.2, random_state=0)

In [26]:
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (40000,)
y_train shape: (40000,)
X_test shape: (10000,)
y_test shape: (10000,)


In [27]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train.values)
X_test_vectorizer = vectorizer.transform(X_test.values)

In [28]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=50, criterion="entropy", random_state=0)
model.fit(X_train_vectorized, y_train)

,n_estimators,50
,criterion,'entropy'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,'sqrt'
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,bootstrap,True
,oob_score,False


In [29]:
from sklearn.metrics import accuracy_score, classification_report

print(f"Accuracy Score: {accuracy_score(y_test, model.predict(X_test_vectorizer))}")
print(f"Classification repost: \n {classification_report(y_test, model.predict(X_test_vectorizer))}")

Accuracy Score: 0.8352


Classification repost: 
               precision    recall  f1-score   support

           0       0.83      0.84      0.84      5035
           1       0.84      0.83      0.83      4965

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000



In [30]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("random_forest_classifier", RandomForestClassifier(n_estimators=50, criterion="entropy", random_state=0))
])

In [31]:
pipeline.fit(X_train, y_train)

,steps,"[('vectorizer', ...), ('random_forest_classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [32]:
print(f"Accuracy Score: {accuracy_score(y_test, pipeline.predict(X_test))}")
print(f"Classification repost: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy Score: 0.8352
Classification repost: 
               precision    recall  f1-score   support

           0       0.83      0.84      0.84      5035
           1       0.84      0.83      0.83      4965

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000



In [33]:
from sklearn.neighbors import KNeighborsClassifier

pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("knn_classifier", KNeighborsClassifier(n_neighbors=10, metric="euclidean"))
])

In [34]:
pipeline.fit(X_train, y_train)

,steps,"[('vectorizer', ...), ('knn_classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None


In [35]:
print(f"Accuracy Score: {accuracy_score(y_test, pipeline.predict(X_test))}")
print(f"Classification repost: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy Score: 0.6558
Classification repost: 
               precision    recall  f1-score   support

           0       0.65      0.67      0.66      5035
           1       0.66      0.64      0.65      4965

    accuracy                           0.66     10000
   macro avg       0.66      0.66      0.66     10000
weighted avg       0.66      0.66      0.66     10000



In [36]:
pipeline = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("naive_bayes_classifier", MultinomialNB())
])

pipeline.fit(X_train, y_train)

print(f"Accuracy Score: {accuracy_score(y_test, pipeline.predict(X_test))}")
print(f"Classification repost: \n {classification_report(y_test, pipeline.predict(X_test))}")

Accuracy Score: 0.844
Classification repost: 
               precision    recall  f1-score   support

           0       0.82      0.88      0.85      5035
           1       0.87      0.81      0.84      4965

    accuracy                           0.84     10000
   macro avg       0.85      0.84      0.84     10000
weighted avg       0.85      0.84      0.84     10000

